export class JDPVehicleInfo {
  id: number;
  vehicleID: number;
  dealerID: number;
  dealerName: string;
  isNew: boolean | null;
  vIN: string;
  stockNumber: string;
  isCertified: boolean | null;
  year: number | null;
  make: string;
  model: string;
  modelCode: string;
  trim: string;
  bodyName: string;
  bodyStyle: string;
  cityMPG: number | null;
  hwyMPG: number | null;
  daysInSotck: number | null;
  valueSource: string;
  exteriorColor: string;
  interiorColor: string;
  interiorMaterial: string;
  engine: string;
  transmission: string;
  transmissionSpeed: string;
  comments: string;
  comments2: string;
  comments3: string;
  comments4: string;
  comments5: string;
  inStockDate: string | null;
  lastModifiedDate: string | null;
  isSpecial: boolean | null;
  bodyType: string;
  locked: boolean | null;
  vehicleStatus: string;
  dealerCertified1: boolean | null;
  dealerCertified2: boolean | null;
  genericExteriorColor: string;
  videoUrl: string;
  drivetrain: string;
  mileage: number | null;
  category1: string;
  category2: string;
  category3: string;
  category4: string;
  category5: string;
  style: string;
  chromeStyleID: number | null;
  zipCode: string;
  exportDealerID: string;
  engineFuelType: string;
  exteriorGenericColorDescription: string;
  exteriorColorCode: string;
  pricingCost: number | null;
  pricingList: number | null;
  pricingSpecial: number | null;
  pricingExtraPrice1: number | null;
  pricingExtraPrice2: number | null;
  pricingExtraPrice3: number | null;
  isActive: boolean | null;
  createdDate: string | null;
  createdBy: number | null;
  updatedDate: string | null;
  updatedBy: number | null;
  deletedDate: string | null;
  deletedBy: number | null;
  isInternalSynch: boolean | null;
  synchedDate: string | null;
  synchedBy: number | null;
  internalID: number | null;
  totalcount: number | null;
}